<testsuites>
	<testsuite name="AllTests" tests="7">
		<testcase classname="AllTests" name="thisIsATest">
			<failure message="../src/Test.cpp:81 thisIsATest: start writing tests">
thisIsATest: start writing tests
			</failure>
		</testcase>
		<testcase classname="AllTests" name="WarehouseHasInventory"/>
		<testcase classname="AllTests" name="WarehouseRemove"/>
		<testcase classname="AllTests" name="WarehouseAdd">
			<failure message="../src/Test.cpp:36 WarehouseAdd: warehouse.hasInventory(TALISKER,50)">
WarehouseAdd: warehouse.hasInventory(TALISKER,50)
			</failure>
		</testcase>
		<testcase classname="AllTests" name="WarehouseGetInventory">
			<failure message="../src/Test.cpp:50 WarehouseGetInventory: 50 == warehouse.getInventory(TALISKER) expected:	50	but was:	0	">
WarehouseGetInventory: 50 == warehouse.getInventory(TALISKER) expected:	50	but was:	0	
			</failure>
		</testcase>
		<testcase classname="AllTests" name="OrderCtor"/>
		<testcase classname="AllTests" name="OrderFillFromWarehouse"/>
	</testsuite>
</testsuites>
